name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies (Node.js)
        run: npm install
        # For Python, use: pip install -r requirements.txt

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          branch: "main"
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "telegram-airport-weather-bot"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
